# Generated by Django 3.0.7 on 2020-07-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enderecoentrega',
            options={'verbose_name_plural': 'Enderecos de entrega'},
        ),
    ]
