# Generated by Django 3.0.7 on 2020-07-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200707_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='preco',
        ),
    ]
