# Generated by Django 3.0.7 on 2020-07-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_itempedido_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tema',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
