# Generated by Django 3.0.7 on 2020-07-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produto_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='dimensoes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tecnica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
