# Generated by Django 3.0.7 on 2020-07-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='obras',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
